
[[mgr.prepend_keymap]]
on   = "<enter>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"


[[manager.prepend_keymap]]
on   = "i"
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

[[manager.prepend_keymap]]
on   = "i"
run  = "plugin toggle-pane --args=max-preview"
desc = "Maximize or restore the preview pane"

