

[[mgr.prepend_keymap]]
on   = "<enter>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"


[[mgr.prepend_keymap]]
on   = "I"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

[[mgr.prepend_keymap]]
on =  "o"
run = "create"
desc = "Create a new file or directory"

